language: php

php:
  - 5.5
  - 7.0 

dist: trusty
sudo: false

before_script:
  - composer self-update
  - composer install --no-interaction --dev

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose
